#!/bin/bash

pacman -S yay --noconfirm
yay -Syu 
yay 
yay -S update-grub opencl-nvidia unrar p7zip nohang --noconfirm
yay -S nvidia-tweaks --noconfirm
yay -S wd719x-firmware ast-firmware upd72020x-fw aic94xx-firmware --noconfirm
yay -S linux-firmware-bnx2x linux-firmware-liquidio linux-firmware-marvell linux-firmware-mellanox linux-firmware-nfp linux-firmware-qcom linux-firmware-qlogic linux-firmware-whence --noconfirm

yay --save --devel

mkinitcpio -P
