#!/bin/bash

systemctl enable ly
systemctl enable nohang

sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/& nvidia-drm.modeset=1 /' /etc/default/grub


update-grub



echo "hide_borders = true" >> /etc/ly/config.ini

sed -i "s/Exec=/&env WLR_NO_HARDWARE_CURSORS=1 /" /usr/share/wayland-sessions/hyprland.desktop



