#!/bin/bash

mkfs.fat -F32 /dev/sd#1

mkfs.ext4 /dev/sd#2

mount /dev/sd#2 /mnt

mkdir -p /mnt/boot/efi

mount /dev/sd#1 /mnt/boot/efi

pacstrap /mnt base linux linux-firmware base-devel git nano wget dhcpcd

genfstab -U /mnt >> /mnt/etc/fstab

git clone https://github.com/tyeistired/ice.git /mnt/ice/

arch-chroot /mnt





