#!/bin/bash

echo en_US.UTF-8 UTF-8 >> /etc/locale.gen

locale-gen

echo LANG=en_US.UTF-8 > /etc/locale.conf

echo ty > /etc/hostname

passwd

pacman -S grub efibootmgr os-prober

grub-install

grub-mkconfig -o /boot/grub/grub.cfg

mkinitcpio -P

pacman -S sudo dhcpcd


systemctl enable dhcpcd

